#!/bin/sh

set -e

repo_root=$(git rev-parse --show-toplevel)

echo "Running backend precommit..."
npm --prefix "$repo_root/backend" run precommit

echo "Running frontend precommit..."
npm --prefix "$repo_root/frontend" run precommit
