services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "production"

  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
      args:
        PUBLIC_URL: ${CMS_PUBLIC_URL}
    environment:
      NODE_ENV: "production"
