networks:
  shared_network:
    external: true
  internal_network:
    name: "${PROJECT_PREFIX}-internal_network"
    driver: bridge

volumes:
  db-data:
  gdrive-data:

services:
  frontend:
    container_name: "${PROJECT_PREFIX}-frontend"
    depends_on:
      - backend
    networks:
      - shared_network
      - internal_network
    environment:
      NITRO_PORT: ${FRONTEND_PORT}
      NUXT_API_URL: ${FRONTEND_API_URL}

  backend:
    container_name: "${PROJECT_PREFIX}-backend"
    networks:
      - internal_network
    depends_on:
      - db
    environment:
      PORT: ${BACKEND_PORT}

      DB_HOST: "${PROJECT_PREFIX}-db"
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}

  db:
    image: postgres:17-alpine
    container_name: "${PROJECT_PREFIX}-db"
    shm_size: 128mb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal_network
    ports:
      - "${POSTGRES_PORT}:5432"

  gdrive-mount:
    image: rclone/rclone:latest
    container_name: gdrive
    command: "mount gdrive: /mnt/gdrive --vfs-cache-mode=off --allow-other --allow-non-empty"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./rclone/rclone.conf:/config/rclone/rclone.conf:ro
      - gdrive-data:/mnt/gdrive
    restart: unless-stopped