FROM node:22.18.0-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci && npm cache clean --force

COPY . .

RUN apk add --no-cache rclone fuse3 bash
RUN mkdir -p /storage
VOLUME ["/storage"]

CMD ["sh", "-c", "rclone mount gdrive: /storage --vfs-cache-mode=off --allow-other --allow-non-empty & npm run start:dev"]
#CMD sh -c 'rclone mount gdrive: /storage --vfs-cache-mode=off --allow-other --allow-non-empty & NODE_OPTIONS="--trace-deprecation" npm run start:dev'
