/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/backend/auth/google": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AuthController_googleAuth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/auth/google/redirect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AuthController_googleAuthRedirect"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["AuthController_refreshToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UsersController_getUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/cards/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["CardsController_getCards"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/sets/topics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SetsController_getTopics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/sets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SetsController_getSets"];
    put?: never;
    post: operations["SetsController_createSet"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/sets/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["SetsController_getSet"];
    put?: never;
    post?: never;
    delete: operations["SetsController_deleteSet"];
    options?: never;
    head?: never;
    patch: operations["SetsController_updateSet"];
    trace?: never;
  };
  "/backend/storage/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["StorageController_uploadFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/storage/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["StorageController_getFiles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/storage/backups/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["StorageController_runBackup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backend/storage/files/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["StorageController_deleteFile"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RefreshTokenDto: {
      refreshToken: string;
    };
    RefreshTokenResponseDto: {
      accessToken: string;
    };
    UserResponseDto: {
      firstName: string;
      lastName: string;
      email: string;
      avatar?: string;
    };
    FileResponseDto: {
      id: string;
      src: string;
      name: string;
    };
    CardDetailsResponseDto: {
      id: string;
      position: number;
      term: string;
      termDescription: string | null;
      termImage: components["schemas"]["FileResponseDto"] | null;
      definition: string;
      definitionImage: components["schemas"]["FileResponseDto"] | null;
      textColor: string | null;
      backgroundColor: string | null;
    };
    TopicResponseDto: {
      id: string;
      label: string;
      value: string;
      icon: string;
      description: string;
    };
    SetListItemResponseDto: {
      id: string;
      name: string;
      description: string;
      topics: components["schemas"]["TopicResponseDto"][];
      user: components["schemas"]["UserResponseDto"];
      cardsCount: number;
    };
    SetDetailsResponseDto: {
      id: string;
      name: string;
      description: string;
      topics: components["schemas"]["TopicResponseDto"][];
      user: components["schemas"]["UserResponseDto"];
      cards: components["schemas"]["CardDetailsResponseDto"][];
    };
    CreateCardDto: {
      position: number;
      term: string;
      termDescription?: string | null;
      termImageId?: string | null;
      definition: string;
      definitionImageId?: string | null;
      textColor?: string | null;
      backgroundColor?: string | null;
    };
    CreateSetDto: {
      name: string;
      description: string;
      topicIds: string[];
      cards: components["schemas"]["CreateCardDto"][];
    };
    SuccessResponseDto: {
      success: boolean;
    };
    UpdateCardDto: {
      position: number;
      term: string;
      termDescription?: string | null;
      termImageId?: string | null;
      definition: string;
      definitionImageId?: string | null;
      textColor?: string | null;
      backgroundColor?: string | null;
      /** Format: uuid */
      id?: string | null;
    };
    UpdateSetDto: {
      name: string;
      description: string;
      topicIds: string[];
      cards: components["schemas"]["UpdateCardDto"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_googleAuth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_googleAuthRedirect: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  AuthController_refreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokenDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefreshTokenResponseDto"];
        };
      };
    };
  };
  UsersController_getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponseDto"];
        };
      };
    };
  };
  UsersController_getUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  CardsController_getCards: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardDetailsResponseDto"][];
        };
      };
    };
  };
  SetsController_getTopics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TopicResponseDto"][];
        };
      };
    };
  };
  SetsController_getSets: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetListItemResponseDto"][];
        };
      };
    };
  };
  SetsController_createSet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSetDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetDetailsResponseDto"];
        };
      };
    };
  };
  SetsController_getSet: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetDetailsResponseDto"];
        };
      };
    };
  };
  SetsController_deleteSet: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponseDto"];
        };
      };
    };
  };
  SetsController_updateSet: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSetDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetDetailsResponseDto"];
        };
      };
    };
  };
  StorageController_uploadFile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileResponseDto"];
        };
      };
    };
  };
  StorageController_getFiles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileResponseDto"][];
        };
      };
    };
  };
  StorageController_runBackup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  StorageController_deleteFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponseDto"];
        };
      };
    };
  };
}

type ApiSchemas = components["schemas"];

export type ICardDetailsResponse = ApiSchemas["CardDetailsResponseDto"];
export type ICreateCard = ApiSchemas["CreateCardDto"];
export type ICreateSet = ApiSchemas["CreateSetDto"];
export type IFileResponse = ApiSchemas["FileResponseDto"];
export type IRefreshToken = ApiSchemas["RefreshTokenDto"];
export type IRefreshTokenResponse = ApiSchemas["RefreshTokenResponseDto"];
export type ISetDetailsResponse = ApiSchemas["SetDetailsResponseDto"];
export type ISetListItemResponse = ApiSchemas["SetListItemResponseDto"];
export type ISuccessResponse = ApiSchemas["SuccessResponseDto"];
export type ITopicResponse = ApiSchemas["TopicResponseDto"];
export type IUpdateCard = ApiSchemas["UpdateCardDto"];
export type IUpdateSet = ApiSchemas["UpdateSetDto"];
export type IUserResponse = ApiSchemas["UserResponseDto"];
