FROM node:22-alpine

ENV NODE_OPTIONS=--max-old-space-size=2048

RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev bash vips-dev git

WORKDIR /opt/app

COPY package*.json ./
RUN npm ci && npm cache clean --force

COPY . .

RUN chown -R node:node /opt/app

USER node

CMD ["npm", "run", "develop"]
