events {}

http {
    server {
        listen 4999;

        charset utf-8;
        client_max_body_size 50M;

        location ^~ /_nuxt/ {
            root /app/.output/public;
            expires 365d;
            add_header Cache-Control "public, no-transform";
            try_files $uri =404;
            access_log off;
            log_not_found off;
        }

        location ~* \.(?:avif|gif|ico|jpe?g|png|svg|webp)$ {
            root /app/.output/public;
            expires 7d;
            add_header Cache-Control "public, no-transform";
            try_files $uri =404;
            access_log off;
            log_not_found off;
        }

        location / {
            proxy_pass http://p-quizpet-frontend:5001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            add_header Cache-Control "no-cache, no-store, max-age=0, must-revalidate";
            add_header Pragma "no-cache";
        }

        location /backend {
            proxy_pass http://p-quizpet-backend:5002;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
