name: Prod Build

on:
  push:
    branches:
      - main

jobs:
  build-prod:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy .env from server
        run: cp /home/petya/projects/quizpet/.env .env

      - name: Copy rclone.conf from server
        run: cp /home/petya/projects/quizpet/rclone/rclone.conf rclone/rclone.conf

      - name: Sync code to server folder
        run: rsync -av --delete ./ /home/petya/projects/quizpet/

      - name: Run make prod
        run: make prod
